#-------------------------------
# GitHub Action part 1 - main
#
# Copyleft (c) by Jest1m 2021.
#-------------------------------

name: CI
env:
  APPLICATION_NAME    : "Flask" 
  DEPLOY_PACKAGE_NAME : "Flask-deploy-ver-${{ github.sha }}"

# Controls when the action will run. 
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ] 	  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Print hello from testing
      run: 
        echo "Hello from testing job"
        
    - name: List current folder
      run:  ls -la
      
    - name: Git clone myrepo
      uses: actions/checkout@v1
      
    - name: List current folder
      run:  ls -la
      
    - name: Execute some commands
      run:
        echo "dasdas"
        echo "Application name is $APPLICATION_NAME"
        
  deploy:
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps:
    - name: Print hello from deploy
      run: 
        echo "Hello from deploy job"
      
    - name: Deploy package
      run:
        echo "Deploy package name is $DEPLOY_PACKAGE_NAME"

    - name: lets test packages 1
      run:  aws --version
      
    - name: lets test packages 1
      run:  zip
